services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-movie-recommender
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: com-movie-recommender-user
      RABBITMQ_DEFAULT_PASS: com-movie-recommender-password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

volumes:
  rabbitmq_data:
  rabbitmq_logs:
