server:
  port: 9005  # Search Service running on port 9005

# JWT configuration
jwt:
  secret: SecretKey12345
  expiration: 86400000

spring:
  application:
    name: search-service
  data:
    mongodb:
      uri: mongodb://user:pass@localhost:27017
      database: movieDB

# Docker-specific configuration
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://user:pass@mongodb:27017
      database: movieDB