server:
  port: 9003  # Crawler runs on port 9003

service:
  location:
    service:
      url: http://location-service:9001
  user:
    service:
      url: http://user-service:9002
spring:
  application:
    name: crawler

  data:
    mongodb:
      uri: mongodb://user:pass@localhost:27017
      database: movieDB

  # RabbitMQ configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: com-movie-recommender-user
    password: com-movie-recommender-password

dataset:
  path: /data/movies.json

# Docker specific configuration
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://user:pass@mongodb:27017
      database: movieDB
  rabbitmq:
    host: rabbitmq