server:
  port: 9003  # Crawler runs on port 9003

service:
  location:
    service:
      url: http://localhost:9001

spring:
  application:
    name: crawler

  data:
    mongodb:
      uri: mongodb://user:pass@localhost:27017
      database: movieDB

  # RabbitMQ configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: com-movie-recommender-user
    password: com-movie-recommender-password

dataset:
  path: D:/University/3_course/1_semestre/Project/movies.json
