server:
  port: 9003  # Crawler runs on port 9003

service:
  location:
    service:
      url: http://localhost:9001
  user:
    service:
      url: http://localhost:9002
spring:
  application:
    name: crawler

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: movieDB

dataset:
  path: /data/movies.json

# Docker-specific configuration
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://user:pass@mongodb:27017
      database: movieDB