server:
  port: 9003  # Crawler runs on port 9003

service:
  location:
    service:
      url: http://localhost:9001

spring:
  application:
    name: crawler

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: movieDB

dataset:
  path: C:/3course_project/data/movies.json


tmdb:
  api:
    key: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ODg1YzczNjY0ZjNmOWQzZTJlNmE0MTk2Mzk4OThhYiIsIm5iZiI6MTczMTExMDQxNy41ODU2NjkzLCJzdWIiOiI2NzAyZjhmOWM5YTEwZDQ2ZWE3ZDY1MjQiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.oNCbIMorq3UNVg1FlMkpdbTIV8r1SH_bz8eq2YPZWh8