server:
  port: 9006  # reco-service runs on port 9006

reco:
  threshold: 0.25

service:
  location:
    service:
      url: http://localhost:9001
  user:
    service:
      url: http://localhost:9002

spring:
  application:
    name: reco-service

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: movieDB
