server:
  port: 9006  # reco-service runs on port 9006

reco:
  threshold: 0.25 # Threshold for recommendations to be considered relevant

# JWT configuration
jwt:
  secret: SecretKey12345
  expiration: 86400000

service:
  location:
    service:
      url: http://location-service:9001
  user:
    service:
      url: http://user-service:9002

spring:
  application:
    name: reco-service

  data:
    mongodb:
      uri: mongodb://user:pass@localhost:27017
      database: movieDB

# Docker-specific configuration
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://user:pass@mongodb:27017
      database: movieDB