server:
  port: 9006  # Crawler runs on port 9004

service:
  location:
    service:
      url: http://localhost:9006

spring:
  application:
    name: reco-service

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: movieDB
